### PR TITLE
First pass on privacy guidance document. Addresses https://github.com/chaoss/community/issues/294

### PR DESCRIPTION
**Pull request by lucasgonze**

### CODE REVIEW

**Comment by lucasgonze** [comment]
giving up

**Comment by germonprez** [comment]
@lucasgonze are you closing this because it is either captured in the way that WGs work or the new data document that is being looked at in the Common WG.... or neither :)

**Comment by germonprez** [comment]
If this is a document that needs work, could I move it to a Google doc?

**Comment by lucasgonze** [comment]
> @lucasgonze are you closing this because it is either captured in the way that WGs work or the new data document that is being looked at in the Common WG.... or neither :)

I am closing it because it didn't get merged and has gotten stale.

**Comment by lucasgonze** [comment]
A Google Doc is fine.

**Comment by germonprez** [comment]
I've created a doc here: https://docs.google.com/document/d/14HD-1B4u0BD5dhh1sel4TxHA1_5NcPELMqK50MrtSRE/edit?usp=sharing

I think we can now talk about this in Common

**Comment by ElizabethN** [comment]
Hi! I do try to check the community repo often. I thought this work was still ongoing, and I didn't realize it was ok to merge this. Usually, we only merge when docs are finished. Sincere apologies @lucasgonze! :pray: 💛

**Comment by lucasgonze** [comment]
No problem, Elizabeth! 

FWIW I measure my own productivity in PRs merged, so when the Google Doc version is done I'm happy to convert it back to a PR.

**Comment by ElizabethN** [comment]
@lucasgonze oh, that would be perfect! Thank you so much! 🙌

**Pull request closed without merging**
