### PR TITLE
Update brand-style-guide.md

### PR DESCRIPTION
**Pull request by LamiWilliams**
Signed off by: Lami Williams <w.olamideesther@gmail.com>

I did the following:
- Added a "Design File" section under "Project Name and Logo" and linked it to the appropriate URL
-  Changed the link embedded in "logos" to the one provided in the issue
- Added a comma after "how it’s expressed"

### CODE REVIEW

**Comment by LamiWilliams** [comment]
Hi @Ruth-ikegah I don't seem to be able to get a hang of how to properly do a DCO.  I did not add it in the first PR I created, so I closed it. For the second PR, I added it, but still had an error. These are what I've tried:

-  Installed the DCO plugin on Chrome an inputted my name and email
- After I merged the PR the second time and still saw the error, I edited the commit to match "what Github expects" in the summary of the DCO error details
- Removed the space between Lami and Williams; had to edit the commit again for this

Could you guide me on how to resolve this? Thanks!

**Comment by Ruth-ikegah** [comment]
Hi @LamiWilliams sorry for this issue!

if you click on details on the dco, do you see "set dco to pass" option?

**Comment by LamiWilliams** [comment]
Thanks, @Ruth-ikegah No, I did not see it. This image shows I see:
screencapture-github-chaoss-community-pull-498-checks-2023-01-23-12_27_47

**Comment by Ruth-ikegah** [comment]
Okay @LamiWilliams I just clicked it on my own end and will be merging this PR! Thank you for your contribution!

**Comment by LamiWilliams** [comment]
Okay, great. Thank you! @Ruth-ikegah

**Pull request merged**
