### PR TITLE
Update GSoC-interest.md

### PR DESCRIPTION
**Pull request by TejasMate**
Signed-off-by: Tejas Mate <hellotejas@pm.me>

### CODE REVIEW

**Comment by vchrombie** [comment]
Hi @TejasMate, thanks for your interest in CHAOSS and for working on the application for the GSoC idea.

I think the GSoC deadline has passed already and it is totally unfair on our side if we want to accept more applications. I'm not sure if you have submitted your proposal on the GSoC website, but the CHAOSS Community wants you to submit the proposal on the GSoC website and also add an entry to the `GSoC-interest.md` which I see you have done in this PR. But, as a rule, that we follow, the applicants have to complete both of these before the GSoC deadline.

> You must complete these things by April 19, 2022, 13:00 US Central Time (UTC-5). Make sure to also [submit the information required by GSoC for applicants](https://summerofcode.withgoogle.com/) (i.e., project proposal), linking to it from your pull request to this file. Here is an [Proposal Template](https://docs.google.com/document/d/1YZez6_hgp2dBybEsMZoQ-ONB9IawK4_OPISLHe9Tjew/edit) to get you started.

The excerpt is taken from https://github.com/chaoss/community/blob/main/GSoC-interest.md

I highly appreciate the hard work and effort by the applicants who have worked on the applications, microtasks & the proposal and completed the things before the GSoC deadline and it is totally unfair to accept any application that is submitted after the deadline which is against what we follow too.

I once again appreciate your efforts in working on this idea but I'm sorry we have to revert this PR since the application wouldn't be accepted by the community.

Tagging the mentors of the project so that they are aware of this @klumb @germonprez @ritik-malik @ElizabethN

**Comment by klumb** [comment]
Hi @vchrombie, thanks for keeping an eye on this but it looks like @TejasMate submitted his proposal to GSOC before the cutoff date and just forgot to add their name here. I am not sure we need to revert this.

**Comment by vchrombie** [comment]
> Hi @vchrombie, thanks for keeping an eye on this but it looks like @TejasMate submitted his proposal to GSOC before the cutoff date and just forgot to add their name here. I am not sure we need to revert this.

Thanks for the clarification @klumb. I wanted to raise this because we have followed this rule in the previous seasons as well and there were cases where we declined to review since they didn't follow the deadlines, for example, https://github.com/chaoss/community/pull/269#issuecomment-819050951.

Also, it is not that we have brought this rule just days before. The deadline was added by Sean when he updated the `GSoC-interest.md` file for this year. https://github.com/chaoss/community/commit/e543ef54229a958a4910d8b5b00b9767bc5226df

Also, I'm sure we have reminded the applicants in the `gsoc-22` channel or in the other channels on multiple occasions about this since this is something CHAOSS follows every year. 

In any case, if the mentors are okay with accepting the application, I don't have objections until they have a fair review. Thanks for your time, I'm turning down the Revert PR https://github.com/chaoss/community/pull/372.

**Comment by klumb** [comment]
Thanks @vchrombie! I would like a few more mentors to weigh in on this but if someone fails to follow a direction, my first question is are they bad at following directions, or are we bad at giving them. With this particular issue, in future, I think it would be wise to add this task as a microtask in each project.

**Comment by vchrombie** [comment]
> With this particular issue, in future, I think it would be wise to add this task as a microtask in each project.

Good idea, agree on this :+1:

**Pull request merged**
