### PR TITLE
DCO setup

### PR DESCRIPTION
**Pull request by SainiAditya1**
Signed-off-by: sainiaditya1 <adityasaini10012001@outlook.com>

created DCOsetup.md

### CODE REVIEW

**Comment by SainiAditya1** [comment]
Added the information about DCO  #485

**Comment by SainiAditya1** [comment]
@ElizabethN please review it..

**Comment by ElizabethN** [comment]
*THANK YOU* @SainiAditya1! This is great! :rocket: ✨

**Comment by SainiAditya1** [comment]
@ElizabethN . looking to contribute more please assigne me some issues...

**Pull request merged**
